"""
BetVector — Match Analysis Narrative Generator (E18-01)
=======================================================
Synthesises model predictions, team features, head-to-head records,
and contextual data into a structured, human-readable match analysis.

This is a **pure Python module** — no Streamlit, no database queries.
It takes the same ``data`` dict that ``match_detail.load_match_data()``
returns and produces a :class:`MatchNarrative` dataclass that any
consumer (dashboard page, email template, API endpoint) can render.

The narrative answers the user's core question:
"Why does the model predict what it predicts?"

Architecture
------------
1. Eight *factor generators* each assess one signal (form, xG, venue,
   H2H, squad value, pressing style, weather, rest days).
2. Each returns an optional :class:`NarrativeFactor` with a significance
   score (0.0–1.0).  Weak signals are filtered; strong ones rise to the
   top.  Only the top 6 factors are shown to prevent information overload.
3. A headline generator summarises the overall prediction strength.
4. A value summary explains whether value bets exist and why.
5. For finished matches, a result comparison shows model accuracy.

Master Plan refs: MP §3 Flow 1 Step 8, MP §8 Design System
"""

from __future__ import annotations

import math
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Tuple


# ============================================================================
# Dataclasses
# ============================================================================

@dataclass
class NarrativeFactor:
    """A single explanatory factor in the match narrative.

    Each factor represents one signal the model uses — form, xG quality,
    venue advantage, etc.  Factors are ranked by *significance* so the UI
    shows only the most meaningful ones.

    Attributes
    ----------
    category : str
        Internal key: "form", "xg", "venue", "h2h", "squad", "pressing",
        "weather", "rest".
    headline : str
        One-line summary, e.g. "Arsenal in strong form".
    detail : str
        Supporting data, e.g. "2.40 PPG over last 5 vs Chelsea's 1.20".
    direction : str
        "positive" (supports prediction), "negative" (works against it),
        or "neutral" (contextual information).
    significance : float
        0.0–1.0, used for ranking and filtering.
    """
    category: str
    headline: str
    detail: str
    direction: str
    significance: float


@dataclass
class NarrativeValueSummary:
    """Summary of value betting opportunities for this match."""
    has_value_bets: bool
    count: int
    best_market: Optional[str] = None
    best_edge: Optional[float] = None
    summary_text: str = ""


@dataclass
class NarrativeResult:
    """Result comparison for a finished match."""
    actual_home_goals: int
    actual_away_goals: int
    predicted_correct_1x2: bool
    predicted_correct_ou25: bool
    result_text: str


@dataclass
class MatchNarrative:
    """Complete narrative for a match, ready for rendering.

    Generated by :func:`generate_match_narrative`.  Contains all pieces
    the UI needs: headline, expected goals, ranked factors, value summary,
    and (for finished matches) a result comparison.
    """
    headline: str
    headline_colour: str           # "green", "yellow", or "text"
    predicted_home_goals: float    # lambda_home from Poisson model
    predicted_away_goals: float    # lambda_away from Poisson model
    home_team: str
    away_team: str
    is_finished: bool
    factors: List[NarrativeFactor] = field(default_factory=list)
    value_summary: Optional[NarrativeValueSummary] = None
    result: Optional[NarrativeResult] = None
    confidence_label: str = "close"  # "strong", "moderate", "close"


# ============================================================================
# Selection / Market label mapping (mirrors picks.py)
# ============================================================================

_SELECTION_LABELS = {
    ("1X2", "home"): "Home Win",
    ("1X2", "draw"): "Draw",
    ("1X2", "away"): "Away Win",
    ("OU25", "over"): "Over 2.5 Goals",
    ("OU25", "under"): "Under 2.5 Goals",
    ("OU15", "over"): "Over 1.5 Goals",
    ("OU15", "under"): "Under 1.5 Goals",
    ("OU35", "over"): "Over 3.5 Goals",
    ("OU35", "under"): "Under 3.5 Goals",
    ("BTTS", "yes"): "Both Teams to Score",
    ("BTTS", "no"): "Both Teams NOT to Score",
}


# ============================================================================
# Helper — safe attribute access
# ============================================================================

def _ga(obj: Any, attr: str) -> Optional[float]:
    """Safe getattr that returns None for missing or non-numeric values."""
    if obj is None:
        return None
    val = getattr(obj, attr, None)
    if val is None:
        return None
    try:
        return float(val)
    except (ValueError, TypeError):
        return None


# ============================================================================
# Factor Generators
# ============================================================================

def _assess_form(
    home_team: str,
    away_team: str,
    hf: Any,
    af: Any,
) -> Optional[NarrativeFactor]:
    """Compare recent form (points per game over last 5 matches).

    Form is measured as PPG: 3.0 = all wins, 0.0 = all losses.
    A gap of ≥0.6 PPG (~2 extra points over 5 games) is significant.
    """
    h_form = _ga(hf, "form_5")
    a_form = _ga(af, "form_5")
    if h_form is None and a_form is None:
        return None

    h_form = h_form or 0.0
    a_form = a_form or 0.0
    gap = abs(h_form - a_form)

    if gap < 0.3:
        return None

    significance = min(gap / 1.5, 1.0)
    better = home_team if h_form > a_form else away_team
    worse = away_team if h_form > a_form else home_team
    better_val = max(h_form, a_form)
    worse_val = min(h_form, a_form)

    return NarrativeFactor(
        category="form",
        headline=f"{better} in stronger recent form",
        detail=(
            f"{better} averaging {better_val:.2f} PPG over last 5 matches "
            f"vs {worse}'s {worse_val:.2f} PPG"
        ),
        direction="positive",
        significance=significance,
    )


def _assess_xg(
    home_team: str,
    away_team: str,
    hf: Any,
    af: Any,
) -> Optional[NarrativeFactor]:
    """Compare expected goals quality (NPxG preferred over raw xG).

    xG (expected goals) measures the quality of chances created.  NPxG
    strips out penalties for a truer picture of open-play attacking quality.
    """
    # Prefer non-penalty xG if available, fall back to raw xG
    h_xg = _ga(hf, "npxg_5") or _ga(hf, "xg_5")
    a_xg = _ga(af, "npxg_5") or _ga(af, "xg_5")
    if h_xg is None and a_xg is None:
        return None

    h_xg = h_xg or 0.0
    a_xg = a_xg or 0.0
    gap = abs(h_xg - a_xg)

    if gap < 0.2:
        return None

    significance = min(gap / 1.0, 1.0)
    better = home_team if h_xg > a_xg else away_team
    label = "NPxG" if _ga(hf, "npxg_5") is not None else "xG"

    # Also mention defensive quality if available
    h_xga = _ga(hf, "npxga_5") or _ga(hf, "xga_5")
    a_xga = _ga(af, "npxga_5") or _ga(af, "xga_5")

    detail = f"{home_team} {label}: {h_xg:.2f}, {away_team} {label}: {a_xg:.2f}"
    if h_xga is not None and a_xga is not None:
        detail += f" (conceding {h_xga:.2f} and {a_xga:.2f} xGA respectively)"

    return NarrativeFactor(
        category="xg",
        headline=f"{better} creating higher-quality chances",
        detail=detail,
        direction="positive",
        significance=significance,
    )


def _assess_venue(
    home_team: str,
    away_team: str,
    hf: Any,
    af: Any,
) -> Optional[NarrativeFactor]:
    """Assess home/away venue-specific performance.

    Some teams are dominant at home but poor away (fortress effect).
    Venue form vs overall form reveals venue-dependent teams.
    """
    h_venue = _ga(hf, "venue_form_5")
    a_venue = _ga(af, "venue_form_5")
    h_overall = _ga(hf, "form_5")
    a_overall = _ga(af, "form_5")

    if h_venue is None and a_venue is None:
        return None

    # Check if home team has a strong home record
    h_boost = (h_venue or 0) - (h_overall or 0) if h_venue and h_overall else 0
    # Check if away team struggles on the road
    a_drop = (a_overall or 0) - (a_venue or 0) if a_venue and a_overall else 0

    max_effect = max(abs(h_boost), abs(a_drop))
    if max_effect < 0.4:
        return None

    significance = min(max_effect / 1.0, 0.8)

    if h_boost > a_drop:
        headline = f"{home_team} strong at home"
        detail = (
            f"{home_team} home form: {h_venue:.2f} PPG "
            f"(overall: {h_overall:.2f})"
        )
    else:
        headline = f"{away_team} weaker away from home"
        detail = (
            f"{away_team} away form: {a_venue:.2f} PPG "
            f"(overall: {a_overall:.2f})"
        )

    return NarrativeFactor(
        category="venue",
        headline=headline,
        detail=detail,
        direction="positive",
        significance=significance,
    )


def _assess_h2h(
    home_team: str,
    away_team: str,
    hf: Any,
    h2h_data: List[dict],
) -> Optional[NarrativeFactor]:
    """Assess head-to-head record between the teams.

    The H2H record from the last 5 meetings captures rivalry effects
    and stylistic matchup advantages.
    """
    h_wins = _ga(hf, "h2h_wins")
    h_draws = _ga(hf, "h2h_draws")
    h_losses = _ga(hf, "h2h_losses")

    if h_wins is None or h_draws is None or h_losses is None:
        return None

    total = int(h_wins + h_draws + h_losses)
    if total == 0:
        return None

    h_wins_int = int(h_wins)
    h_losses_int = int(h_losses)

    # Dominant record (≥4 wins out of 5) = high significance
    if h_wins_int >= 4:
        significance = 0.7
        headline = f"{home_team} dominates this fixture"
    elif h_losses_int >= 4:
        significance = 0.7
        headline = f"{away_team} dominates this fixture"
    elif h_wins_int >= 3:
        significance = 0.5
        headline = f"{home_team} holds the H2H advantage"
    elif h_losses_int >= 3:
        significance = 0.5
        headline = f"{away_team} holds the H2H advantage"
    else:
        significance = 0.2
        headline = "Evenly matched in recent meetings"

    # Build detail with goals info
    h2h_gs = _ga(hf, "h2h_goals_scored")
    h2h_gc = _ga(hf, "h2h_goals_conceded")
    detail = f"Last {total} meetings: {home_team} {h_wins_int}W {int(h_draws)}D {h_losses_int}L"
    if h2h_gs is not None and h2h_gc is not None:
        avg_total = h2h_gs + h2h_gc
        detail += f" (avg {avg_total:.1f} goals per match)"

    return NarrativeFactor(
        category="h2h",
        headline=headline,
        detail=detail,
        direction="positive" if h_wins_int > h_losses_int else (
            "negative" if h_losses_int > h_wins_int else "neutral"
        ),
        significance=significance,
    )


def _assess_squad_value(
    home_team: str,
    away_team: str,
    hf: Any,
    af: Any,
    home_mv: Optional[dict],
    away_mv: Optional[dict],
) -> Optional[NarrativeFactor]:
    """Compare squad market values from Transfermarkt.

    Market value is a proxy for long-term squad quality — transfer spending,
    squad depth, and talent ceiling.  A ratio > 2.0 means one squad is
    worth double the other, a substantial quality gap.
    """
    ratio = _ga(hf, "market_value_ratio")
    if ratio is None or (0.8 <= ratio <= 1.25):
        return None

    # Prevent math domain errors
    if ratio <= 0:
        return None

    significance = min(abs(math.log2(ratio)) / 3.0, 1.0)

    richer = home_team if ratio > 1.0 else away_team
    ratio_display = ratio if ratio >= 1.0 else 1.0 / ratio

    # Include absolute values if we have market value dicts
    value_detail = ""
    if home_mv and away_mv:
        h_val = home_mv.get("squad_total_value", 0)
        a_val = away_mv.get("squad_total_value", 0)
        if h_val and a_val:
            value_detail = (
                f" ({home_team}: €{h_val/1e6:.0f}m, "
                f"{away_team}: €{a_val/1e6:.0f}m)"
            )

    return NarrativeFactor(
        category="squad",
        headline=f"{richer} has significantly stronger squad",
        detail=f"Squad value ratio: {ratio_display:.1f}x in favour of {richer}{value_detail}",
        direction="positive" if ratio > 1.0 else "negative",
        significance=significance,
    )


def _assess_pressing(
    home_team: str,
    away_team: str,
    hf: Any,
    af: Any,
) -> Optional[NarrativeFactor]:
    """Compare PPDA (Passes Per Defensive Action) to identify style clashes.

    Low PPDA = aggressive pressing (Liverpool ~8, Arsenal ~9).
    High PPDA = sit deep and counter (Burnley ~18, Crystal Palace ~16).
    A clash between pressing and deep-block styles is tactically notable.
    """
    h_ppda = _ga(hf, "ppda_5")
    a_ppda = _ga(af, "ppda_5")
    if h_ppda is None or a_ppda is None:
        return None

    gap = abs(h_ppda - a_ppda)
    if gap < 3.0:
        return None

    significance = min(gap / 10.0, 0.7)

    presser = home_team if h_ppda < a_ppda else away_team
    blocker = away_team if h_ppda < a_ppda else home_team
    presser_ppda = min(h_ppda, a_ppda)
    blocker_ppda = max(h_ppda, a_ppda)

    return NarrativeFactor(
        category="pressing",
        headline=f"Style clash: {presser} pressing vs {blocker} deep block",
        detail=(
            f"{presser} PPDA: {presser_ppda:.1f} (aggressive pressing) vs "
            f"{blocker}: {blocker_ppda:.1f} (sits deeper)"
        ),
        direction="neutral",
        significance=significance,
    )


def _assess_weather(
    weather: Optional[dict],
    hf: Any,
) -> Optional[NarrativeFactor]:
    """Flag significant weather conditions that affect match outcomes.

    Heavy rain reduces passing accuracy and favours direct, physical play.
    Strong wind makes long balls unpredictable.  Both tend to reduce
    goal-scoring rates, favouring Unders.
    """
    if weather is None:
        return None

    # Check the is_heavy_weather flag from feature data
    is_heavy = _ga(hf, "is_heavy_weather")
    if not is_heavy or is_heavy < 1:
        # Also check weather dict directly
        precip = weather.get("precipitation_mm") or 0
        wind = weather.get("wind_speed_kmh") or 0
        if precip < 2 and wind < 30:
            return None

    temp = weather.get("temperature_c")
    wind = weather.get("wind_speed_kmh") or 0
    precip = weather.get("precipitation_mm") or 0
    category = (weather.get("weather_category") or "").lower()

    # Determine significance by severity
    if category in ("heavy_rain", "storm", "snow"):
        significance = 0.5
    elif category == "rain" or precip >= 2:
        significance = 0.4
    elif wind >= 30:
        significance = 0.3
    else:
        significance = 0.25

    # Build description parts
    parts = []
    if precip > 0:
        parts.append(f"{precip:.1f}mm rain")
    if wind > 0:
        parts.append(f"{wind:.0f} km/h wind")
    if temp is not None:
        parts.append(f"{temp:.0f}°C")

    return NarrativeFactor(
        category="weather",
        headline="Adverse weather likely to affect play",
        detail=(
            f"Conditions: {', '.join(parts)}. "
            "Heavy weather typically reduces goal-scoring and favours direct play."
        ),
        direction="neutral",
        significance=significance,
    )


def _assess_rest_days(
    home_team: str,
    away_team: str,
    hf: Any,
    af: Any,
) -> Optional[NarrativeFactor]:
    """Flag significant rest day imbalances between the teams.

    A team with 3 rest days playing against one with 7 rest days faces
    measurable fatigue disadvantage — recovery, preparation time, and
    rotation needs all favour the more rested side.
    """
    h_rest = _ga(hf, "rest_days")
    a_rest = _ga(af, "rest_days")
    if h_rest is None or a_rest is None:
        return None

    gap = abs(h_rest - a_rest)
    if gap < 2:
        return None

    significance = min(gap / 5.0, 0.6)
    rested = home_team if h_rest > a_rest else away_team
    tired = away_team if h_rest > a_rest else home_team
    rested_days = max(h_rest, a_rest)
    tired_days = min(h_rest, a_rest)

    return NarrativeFactor(
        category="rest",
        headline=f"{rested} better rested ahead of this match",
        detail=(
            f"{rested}: {rested_days:.0f} days rest vs "
            f"{tired}: {tired_days:.0f} days rest"
        ),
        direction="positive" if h_rest > a_rest else "negative",
        significance=significance,
    )


# ============================================================================
# Factor Ranking
# ============================================================================

def _rank_and_filter_factors(
    factors: List[NarrativeFactor],
    max_factors: int = 6,
    min_significance: float = 0.15,
) -> List[NarrativeFactor]:
    """Rank factors by significance and return the top N.

    Removes factors below the minimum significance threshold, sorts by
    significance descending, then takes at most *max_factors*.  This
    prevents information overload — the user sees only the strongest
    signals driving the prediction.
    """
    meaningful = [f for f in factors if f.significance >= min_significance]
    meaningful.sort(key=lambda f: f.significance, reverse=True)
    return meaningful[:max_factors]


# ============================================================================
# Headline Generator
# ============================================================================

def _generate_headline(
    home_team: str,
    away_team: str,
    pred: Any,
) -> Tuple[str, str, str]:
    """Generate the narrative headline from prediction probabilities.

    Returns ``(headline_text, colour_name, confidence_label)``.

    Thresholds:
    - ≥65% dominant probability → "strongly favours" (green)
    - 55–65% → "favours" (yellow)
    - <55% → "tight match" (white/text)
    """
    ph = getattr(pred, "prob_home_win", 0) or 0
    pd_ = getattr(pred, "prob_draw", 0) or 0
    pa = getattr(pred, "prob_away_win", 0) or 0

    max_prob = max(ph, pd_, pa)

    if ph == max_prob:
        team = home_team
        pct = ph
    elif pa == max_prob:
        team = away_team
        pct = pa
    else:
        # Draw is the most likely outcome — unusual, note it
        return (
            f"Model sees a tight match (Draw {pd_:.0%})",
            "text",
            "close",
        )

    pct_display = f"{pct:.0%}"

    if pct >= 0.65:
        return (
            f"Model strongly favours {team} ({pct_display})",
            "green",
            "strong",
        )
    elif pct >= 0.55:
        return (
            f"Model favours {team} ({pct_display})",
            "yellow",
            "moderate",
        )
    else:
        return (
            f"Model sees a tight match — slight edge to {team} ({pct_display})",
            "text",
            "close",
        )


# ============================================================================
# Value Summary Generator
# ============================================================================

def _generate_value_summary(
    value_bets: List[dict],
    home_team: str,
    away_team: str,
) -> NarrativeValueSummary:
    """Summarise value betting opportunities for this match.

    If value bets exist, highlights the best opportunity.  If none,
    explains that the model broadly agrees with bookmaker pricing.
    """
    if not value_bets:
        return NarrativeValueSummary(
            has_value_bets=False,
            count=0,
            summary_text=(
                "No value bets identified. The model's probabilities "
                "broadly align with bookmaker odds for this match."
            ),
        )

    # Find the best value bet by edge
    best = max(value_bets, key=lambda vb: vb.get("edge", 0))
    best_label = _SELECTION_LABELS.get(
        (best.get("market_type", ""), best.get("selection", "")),
        f"{best.get('market_type', '')}/{best.get('selection', '')}",
    )
    best_edge = best.get("edge", 0) * 100
    best_odds = best.get("bookmaker_odds", 0)

    count = len(value_bets)
    s = "s" if count > 1 else ""

    return NarrativeValueSummary(
        has_value_bets=True,
        count=count,
        best_market=best_label,
        best_edge=best.get("edge", 0),
        summary_text=(
            f"{count} value bet{s} found. Best: {best_label} "
            f"with +{best_edge:.1f}% edge at {best_odds:.2f} odds."
        ),
    )


# ============================================================================
# Result Comparison (finished matches only)
# ============================================================================

def _generate_result_comparison(
    home_goals: int,
    away_goals: int,
    pred: Any,
    home_team: str,
    away_team: str,
) -> NarrativeResult:
    """Compare the model's prediction against the actual result.

    For finished matches, tells the user whether the model got it right
    on the 1X2 outcome and the Over/Under 2.5 market.
    """
    # Actual outcome
    if home_goals > away_goals:
        actual_1x2 = "home"
        actual_label = f"{home_team} win"
    elif away_goals > home_goals:
        actual_1x2 = "away"
        actual_label = f"{away_team} win"
    else:
        actual_1x2 = "draw"
        actual_label = "draw"

    # Predicted outcome (highest probability)
    ph = getattr(pred, "prob_home_win", 0) or 0
    pd_ = getattr(pred, "prob_draw", 0) or 0
    pa = getattr(pred, "prob_away_win", 0) or 0
    max_prob = max(ph, pd_, pa)

    if ph == max_prob:
        predicted_1x2 = "home"
    elif pa == max_prob:
        predicted_1x2 = "away"
    else:
        predicted_1x2 = "draw"

    correct_1x2 = actual_1x2 == predicted_1x2

    # Over/Under 2.5
    total_goals = home_goals + away_goals
    actual_over = total_goals > 2.5
    prob_over = getattr(pred, "prob_over_25", 0) or 0
    predicted_over = prob_over >= 0.5
    correct_ou25 = actual_over == predicted_over

    # Build result text
    lambda_h = getattr(pred, "predicted_home_goals", 0) or 0
    lambda_a = getattr(pred, "predicted_away_goals", 0) or 0

    if correct_1x2:
        text = (
            f"Result: {home_goals}-{away_goals}. "
            f"Model correctly predicted a {actual_label}. "
            f"Expected {lambda_h:.1f}-{lambda_a:.1f} goals."
        )
    else:
        pred_label = (
            f"{home_team} win" if predicted_1x2 == "home"
            else f"{away_team} win" if predicted_1x2 == "away"
            else "draw"
        )
        text = (
            f"Result: {home_goals}-{away_goals}. "
            f"Model predicted {pred_label} but the match ended in a {actual_label}. "
            f"Expected {lambda_h:.1f}-{lambda_a:.1f} goals."
        )

    return NarrativeResult(
        actual_home_goals=home_goals,
        actual_away_goals=away_goals,
        predicted_correct_1x2=correct_1x2,
        predicted_correct_ou25=correct_ou25,
        result_text=text,
    )


# ============================================================================
# Main Orchestrator
# ============================================================================

def generate_match_narrative(data: dict) -> Optional[MatchNarrative]:
    """Generate a complete match narrative from loaded match data.

    This is the primary entry point.  Takes the same ``data`` dict
    returned by ``match_detail.load_match_data()`` and produces a
    :class:`MatchNarrative` ready for rendering.

    Parameters
    ----------
    data : dict
        Match data dict with keys: home_team, away_team, prediction,
        home_features, away_features, weather, home_market_value,
        away_market_value, value_bets, h2h, status, home_goals, away_goals.

    Returns
    -------
    MatchNarrative or None
        None if no prediction exists for this match.
    """
    pred = data.get("prediction")
    if pred is None:
        return None

    hf = data.get("home_features")
    af = data.get("away_features")
    home_team = data["home_team"]
    away_team = data["away_team"]

    # --- Headline ---
    headline, headline_colour, confidence_label = _generate_headline(
        home_team, away_team, pred,
    )

    # --- Collect candidate factors ---
    candidates: List[Optional[NarrativeFactor]] = [
        _assess_form(home_team, away_team, hf, af),
        _assess_xg(home_team, away_team, hf, af),
        _assess_venue(home_team, away_team, hf, af),
        _assess_h2h(home_team, away_team, hf, data.get("h2h", [])),
        _assess_squad_value(
            home_team, away_team, hf, af,
            data.get("home_market_value"), data.get("away_market_value"),
        ),
        _assess_pressing(home_team, away_team, hf, af),
        _assess_weather(data.get("weather"), hf),
        _assess_rest_days(home_team, away_team, hf, af),
    ]

    # Filter Nones and rank by significance
    factors = _rank_and_filter_factors(
        [f for f in candidates if f is not None],
        max_factors=6,
    )

    # --- Value summary ---
    value_summary = _generate_value_summary(
        data.get("value_bets", []), home_team, away_team,
    )

    # --- Result comparison (finished matches only) ---
    is_finished = (
        data.get("status") == "finished"
        and data.get("home_goals") is not None
        and data.get("away_goals") is not None
    )
    result = None
    if is_finished:
        result = _generate_result_comparison(
            data["home_goals"], data["away_goals"],
            pred, home_team, away_team,
        )

    # --- Expected goals (lambda values from Poisson) ---
    lambda_h = getattr(pred, "predicted_home_goals", 0) or 0
    lambda_a = getattr(pred, "predicted_away_goals", 0) or 0

    return MatchNarrative(
        headline=headline,
        headline_colour=headline_colour,
        predicted_home_goals=lambda_h,
        predicted_away_goals=lambda_a,
        home_team=home_team,
        away_team=away_team,
        is_finished=is_finished,
        factors=factors,
        value_summary=value_summary,
        result=result,
        confidence_label=confidence_label,
    )
