"""
BetVector — Poisson Regression Model (E5-02)
==============================================
BetVector's foundational prediction model.  Uses Poisson regression to
estimate the expected number of goals each team will score, then builds
a 7×7 scoreline probability matrix from those estimates.

How the Poisson Model Works
---------------------------
The **Poisson distribution** models the probability of a given number of
events (goals) occurring in a fixed interval (a match), given a known
average rate (lambda).  It's the standard starting point for football
prediction because:

  1. Goals are relatively rare events (typically 1-3 per team per match)
  2. They occur roughly independently of each other
  3. The rate of scoring depends on team quality and matchup

The model estimates two lambda values per match:
  - **lambda_home** (expected home goals) = f(home_attack, away_defence, home_advantage)
  - **lambda_away** (expected away goals) = f(away_attack, home_defence)

Attack Strength and Defence Strength
-------------------------------------
Each team has an **attack strength** (how many goals they tend to score)
and a **defence strength** (how many goals they tend to concede).  These
are estimated from rolling features like goals_scored_5, goals_conceded_5,
xg_5, etc.

The **home advantage** effect is real and significant in football — home
teams score roughly 0.3 more goals per match on average.  The model
learns this from the data.

Building the Scoreline Matrix
-----------------------------
Once we have lambda_home and lambda_away, we compute the probability of
every scoreline from 0-0 to 6-6:

    P(home=h, away=a) = poisson.pmf(h, lambda_home) × poisson.pmf(a, lambda_away)

This assumes **independence** between home and away goals — a simplifying
assumption that works well in practice for match-level predictions.
The matrix is truncated at 6 goals and renormalised so all 49 cells sum
to exactly 1.0.

Why Independence Works (Mostly)
-------------------------------
The independence assumption means we treat "Arsenal scoring 2" and
"Chelsea scoring 1" as independent events.  In reality there's a weak
correlation (e.g., a team chasing a deficit may score more but also
concede more).  However, this correlation is small enough that the
independent Poisson model remains competitive with more complex models.
The ensemble system (future) can combine Poisson with correlation-aware
models for better accuracy.

Master Plan refs: MP §4 Prediction Models, MP §5 Scoreline Matrix, MP §7 Model Interface
"""

from __future__ import annotations

import json
import logging
import pickle
from pathlib import Path
from typing import Any, Dict, List, Optional

import numpy as np
import pandas as pd
from scipy.stats import poisson
from statsmodels.genmod.families import Poisson as PoissonFamily
from statsmodels.genmod.generalized_linear_model import GLM

from src.models.base_model import (
    BaseModel,
    MatchPrediction,
    derive_market_probabilities,
)

logger = logging.getLogger(__name__)

# Maximum goals per team in the scoreline matrix (0 through MAX_GOALS)
MAX_GOALS = 7  # From config: scoreline_matrix.max_goals


class PoissonModel(BaseModel):
    """Poisson regression prediction model.

    Trains two separate Poisson GLMs:
      - **Home goals model:** predicts home team goals from features
      - **Away goals model:** predicts away team goals from features

    Each model learns attack strength, defence strength, and (for home)
    the home advantage effect from historical data.

    After training, predictions are generated by:
      1. Feeding match features through both models → lambda_home, lambda_away
      2. Building a 7×7 scoreline matrix from the Poisson PMFs
      3. Deriving all market probabilities from the matrix
    """

    def __init__(self) -> None:
        self._home_model: Optional[Any] = None  # Fitted GLM for home goals
        self._away_model: Optional[Any] = None  # Fitted GLM for away goals
        self._feature_cols: List[str] = []  # Column names used in training
        self._is_trained = False

    @property
    def name(self) -> str:
        return "poisson_v1"

    @property
    def version(self) -> str:
        return "1.0.0"

    # --- Training ---------------------------------------------------------------

    def train(
        self,
        features: pd.DataFrame,
        results: pd.DataFrame,
    ) -> None:
        """Train Poisson regression models for home and away goals.

        Fits two separate GLMs with a Poisson family and log link:
          - Home goals ~ home_form_5 + home_goals_scored_5 + away_goals_conceded_5 + ...
          - Away goals ~ away_form_5 + away_goals_scored_5 + home_goals_conceded_5 + ...

        Parameters
        ----------
        features : pd.DataFrame
            Training features from ``compute_all_features()``.
            Must contain ``match_id`` and home_*/away_* feature columns.
        results : pd.DataFrame
            Match results with columns: ``match_id``, ``home_goals``, ``away_goals``.
        """
        logger.info("Training Poisson model on %d matches", len(features))

        # Merge features with results
        df = features.merge(results, on="match_id", how="inner")

        # Drop rows with missing target (unplayed matches)
        df = df.dropna(subset=["home_goals", "away_goals"])

        if len(df) < 20:
            raise ValueError(
                f"Not enough training data: {len(df)} matches "
                f"(need at least 20)"
            )

        # Select feature columns for each model
        # Home goals model: uses home team's attacking features + away team's defensive features
        home_feature_cols = self._select_feature_cols(df, target="home")
        away_feature_cols = self._select_feature_cols(df, target="away")

        # Use the union of both feature sets (they may overlap)
        self._feature_cols = sorted(
            set(home_feature_cols) | set(away_feature_cols)
        )

        # Fill NaN features: first try column mean, then 0.0 for columns
        # that are entirely NaN (e.g., xG columns when FBref is unavailable).
        # Drop any columns that remain all-NaN after filling — they provide
        # no signal and cause statsmodels to error.
        X_home = df[home_feature_cols].apply(pd.to_numeric, errors="coerce")
        X_away = df[away_feature_cols].apply(pd.to_numeric, errors="coerce")

        X_home = X_home.fillna(X_home.mean()).fillna(0.0).infer_objects(copy=False)
        X_away = X_away.fillna(X_away.mean()).fillna(0.0).infer_objects(copy=False)

        # Drop columns that are constant (all same value) — they cause
        # multicollinearity with the intercept
        home_varying = X_home.columns[X_home.nunique() > 1].tolist()
        away_varying = X_away.columns[X_away.nunique() > 1].tolist()

        if len(home_varying) < len(home_feature_cols):
            dropped = set(home_feature_cols) - set(home_varying)
            logger.info("Dropped constant home columns: %s", dropped)
            home_feature_cols = home_varying

        if len(away_varying) < len(away_feature_cols):
            dropped = set(away_feature_cols) - set(away_varying)
            logger.info("Dropped constant away columns: %s", dropped)
            away_feature_cols = away_varying

        X_home = X_home[home_feature_cols]
        X_away = X_away[away_feature_cols]

        # Add constant (intercept) for GLM
        X_home = self._add_constant(X_home)
        X_away = self._add_constant(X_away)

        y_home = df["home_goals"].astype(float)
        y_away = df["away_goals"].astype(float)

        # Fit Poisson GLM for home goals
        # The log link means: log(expected_goals) = β₀ + β₁×feature₁ + ...
        # So expected_goals = exp(β₀ + β₁×feature₁ + ...)
        logger.info(
            "Fitting home goals model (%d features)", len(home_feature_cols),
        )
        self._home_model = GLM(
            y_home, X_home, family=PoissonFamily(),
        ).fit()

        logger.info(
            "Fitting away goals model (%d features)", len(away_feature_cols),
        )
        self._away_model = GLM(
            y_away, X_away, family=PoissonFamily(),
        ).fit()

        self._home_feature_cols = home_feature_cols
        self._away_feature_cols = away_feature_cols
        self._is_trained = True

        # Log model summary
        logger.info(
            "Home model AIC=%.1f, Away model AIC=%.1f",
            self._home_model.aic, self._away_model.aic,
        )

    # --- Prediction -------------------------------------------------------------

    def predict(
        self,
        features: pd.DataFrame,
    ) -> List[MatchPrediction]:
        """Generate predictions for matches.

        For each match:
          1. Feed features through both GLMs → lambda_home, lambda_away
          2. Build 7×7 scoreline matrix from Poisson PMFs
          3. Derive market probabilities from the matrix

        Parameters
        ----------
        features : pd.DataFrame
            Match features (same columns as training data).
            Must contain ``match_id``.

        Returns
        -------
        list[MatchPrediction]
            One prediction per match.
        """
        if not self._is_trained:
            raise RuntimeError("Model not trained — call train() first")

        predictions: List[MatchPrediction] = []

        for _, row in features.iterrows():
            match_id = int(row["match_id"])

            # Prepare feature vectors
            X_home = row[self._home_feature_cols].to_frame().T
            X_away = row[self._away_feature_cols].to_frame().T

            # Fill NaN with 0 (conservative fallback for missing features)
            X_home = X_home.astype(float).fillna(0.0)
            X_away = X_away.astype(float).fillna(0.0)

            # Reset index so .iloc[0] works reliably
            X_home = X_home.reset_index(drop=True)
            X_away = X_away.reset_index(drop=True)

            X_home = self._add_constant(X_home)
            X_away = self._add_constant(X_away)

            # Predict expected goals (lambda values)
            # The GLM predict() returns the expected value on the response scale
            # (i.e., exp() already applied due to log link)
            lambda_home = float(self._home_model.predict(X_home).iloc[0])
            lambda_away = float(self._away_model.predict(X_away).iloc[0])

            # Clamp lambda to reasonable range [0.2, 3.5]
            # - 3.5 goals is already extreme (e.g., Man City vs newly promoted)
            #   5.0 was too generous and produced 98.6% home-win probabilities
            # - 0.2 minimum prevents near-zero probabilities in the scoreline matrix
            # Log a warning when the clamp activates — it usually indicates
            # degenerate feature data (missing features → fillna(0.0) → extreme λ)
            LAMBDA_MIN, LAMBDA_MAX = 0.2, 3.5
            raw_home, raw_away = lambda_home, lambda_away
            lambda_home = max(LAMBDA_MIN, min(LAMBDA_MAX, lambda_home))
            lambda_away = max(LAMBDA_MIN, min(LAMBDA_MAX, lambda_away))
            if raw_home != lambda_home or raw_away != lambda_away:
                logger.warning(
                    "Lambda clamped for match %d: raw (%.3f, %.3f) → clamped (%.3f, %.3f). "
                    "Check feature data for missing/degenerate values.",
                    match_id, raw_home, raw_away, lambda_home, lambda_away,
                )

            # Build the 7×7 scoreline probability matrix
            matrix = self._build_scoreline_matrix(lambda_home, lambda_away)

            # Derive all market probabilities from the matrix
            market_probs = derive_market_probabilities(matrix)

            pred = MatchPrediction(
                match_id=match_id,
                model_name=self.name,
                model_version=self.version,
                predicted_home_goals=round(lambda_home, 4),
                predicted_away_goals=round(lambda_away, 4),
                scoreline_matrix=matrix,
                **market_probs,
            )
            predictions.append(pred)

        logger.info("Generated %d predictions", len(predictions))
        return predictions

    # --- Save/Load --------------------------------------------------------------

    def save(self, path: Path) -> None:
        """Save the trained model to disk using pickle.

        Saves the fitted GLM objects, feature column lists, and metadata.
        """
        if not self._is_trained:
            raise RuntimeError("Cannot save untrained model")

        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)

        state = {
            "name": self.name,
            "version": self.version,
            "home_model": self._home_model,
            "away_model": self._away_model,
            "home_feature_cols": self._home_feature_cols,
            "away_feature_cols": self._away_feature_cols,
            "feature_cols": self._feature_cols,
        }
        with open(path, "wb") as f:
            pickle.dump(state, f)

        logger.info("Saved Poisson model to %s", path)

    def load(self, path: Path) -> None:
        """Load a previously trained model from disk."""
        path = Path(path)
        if not path.exists():
            raise FileNotFoundError(f"Model file not found: {path}")

        with open(path, "rb") as f:
            state = pickle.load(f)

        self._home_model = state["home_model"]
        self._away_model = state["away_model"]
        self._home_feature_cols = state["home_feature_cols"]
        self._away_feature_cols = state["away_feature_cols"]
        self._feature_cols = state["feature_cols"]
        self._is_trained = True

        logger.info("Loaded Poisson model from %s", path)

    # --- Internal helpers -------------------------------------------------------

    @staticmethod
    def _select_feature_cols(
        df: pd.DataFrame,
        target: str,
    ) -> List[str]:
        """Select feature columns for home or away goals prediction.

        For home goals, we use:
          - Home team's attacking features (form, goals scored, xG, shots, NPxG, deep)
          - Away team's defensive features (goals conceded, xGA, NPxGA, PPDA allowed)
          - Context features (rest days, H2H)

        For away goals, the mirror: away attacking + home defensive.

        Feature selection rationale (E16-01):
          - NPxG (non-penalty xG) is more predictive than raw xG because it
            strips penalty xG (~76% conversion regardless of team).  We add
            npxg_5 as an attack feature and npxga_5 as a defence feature.
          - PPDA measures pressing intensity — teams with low PPDA create more
            turnovers and chances.  We add ppda_5 to attack (pressing teams
            score more) and ppda_allowed_5 to defence.
          - Deep completions measure quality of attacking buildup — passes
            reaching the opponent's penalty area.  We add deep_5 to attack.
        """
        if target == "home":
            # Home attack features
            attack_prefix = "home_"
            defence_prefix = "away_"
        else:
            attack_prefix = "away_"
            defence_prefix = "home_"

        # Attacking features: how good is this team at scoring?
        attack_cols = [
            f"{attack_prefix}form_5",
            f"{attack_prefix}form_10",
            f"{attack_prefix}goals_scored_5",
            f"{attack_prefix}goals_scored_10",
            f"{attack_prefix}shots_on_target_5",
            f"{attack_prefix}venue_form_5",
            f"{attack_prefix}venue_goals_scored_5",
            # --- Advanced attack features (E16-01) ---
            # NPxG is strictly more predictive than raw xG — strips penalty
            # randomness.  Using 5-match window for responsiveness.
            f"{attack_prefix}npxg_5",
            # Deep completions measure quality of attacking buildup — passes
            # reaching the opponent's penalty area.  High deep = dangerous
            # team that penetrates defences.
            f"{attack_prefix}deep_5",
            # --- Set-piece xG breakdown (E22-01) ---
            # set_piece_xg_5: rolling average set-piece xG.  Teams with tall
            # squads or specialist set-piece takers produce consistently high
            # values — a persistent attacking "skill" separate from open play.
            f"{attack_prefix}set_piece_xg_5",
            # open_play_xg_5: rolling average open-play xG.  Pure measure of
            # live-ball attacking quality, independent of dead-ball situations.
            f"{attack_prefix}open_play_xg_5",
        ]

        # Defensive features: how bad is the opponent at defending?
        defence_cols = [
            f"{defence_prefix}goals_conceded_5",
            f"{defence_prefix}goals_conceded_10",
            f"{defence_prefix}venue_goals_conceded_5",
            # --- Advanced defence features (E16-01) ---
            # NPxGA: non-penalty xG allowed.  Measures the quality of chances
            # the opponent concedes in open play (excluding penalties).
            f"{defence_prefix}npxga_5",
            # PPDA allowed: how much pressing does the opponent face?  Teams
            # that face high pressing (low ppda_allowed) struggle to build up.
            f"{defence_prefix}ppda_allowed_5",
        ]

        # Context features
        context_cols = [
            f"{attack_prefix}rest_days",
            f"{attack_prefix}h2h_goals_scored",
            # --- Market value & weather features (E16-02) ---
            # Market value ratio: richer squads score more — a €1B squad
            # vs a €200M squad has a structural quality advantage.
            f"{attack_prefix}market_value_ratio",
            # Heavy weather (rain >2mm or wind >30km/h) reduces scoring rates
            # on average — wet pitch and unpredictable long balls.
            f"{attack_prefix}is_heavy_weather",
            # --- Market-implied features (E20-01, E20-02) ---
            # Pinnacle implied probabilities: the market's best estimate of
            # each outcome.  Overround-removed so they sum to 1.0.
            # For home goals model: high home_prob → more home goals expected.
            # For away goals model: high away_prob → more away goals expected.
            f"{attack_prefix}pinnacle_home_prob",
            f"{attack_prefix}pinnacle_draw_prob",
            f"{attack_prefix}pinnacle_away_prob",
            # Asian Handicap line: the sharpest market-implied strength
            # difference.  AH = -1.5 means market expects home to win by ~1.5.
            # Negative = stronger team, positive = weaker team.
            f"{attack_prefix}ah_line",
            # --- Elo rating features (E21-01) ---
            # Elo captures long-term team quality beyond rolling form.
            # elo_rating: absolute team strength (higher = better).
            # elo_diff: this team's Elo minus opponent's Elo (positive = stronger).
            # Especially valuable early season and for promoted teams.
            f"{attack_prefix}elo_rating",
            f"{attack_prefix}elo_diff",
            # --- Referee features (E21-02) ---
            # Referee tendencies affect scoring rates.  Goal-permissive refs
            # produce higher-scoring matches.  Home bias refs amplify home advantage.
            f"{attack_prefix}ref_avg_goals",
            f"{attack_prefix}ref_home_win_pct",
            # --- Fixture congestion features (E21-03) ---
            # Binary flag for <4-day rest.  Congested teams press less,
            # rotate more, and score fewer goals on average.
            f"{attack_prefix}is_congested",
            # --- Injury impact features (E22-02) ---
            # injury_impact = sum of impact ratings for absent players.
            # Higher value = more/better players missing = fewer goals expected.
            f"{attack_prefix}injury_impact",
            # key_player_out = binary flag for star player absence.
            # Losing a 1.0-rated player (Haaland, Salah) has outsized impact.
            f"{attack_prefix}key_player_out",
        ]

        # Only include columns that exist in the DataFrame
        all_candidates = attack_cols + defence_cols + context_cols
        available = [c for c in all_candidates if c in df.columns]

        if not available:
            raise ValueError(
                f"No feature columns found for {target} goals model. "
                f"Expected columns like {all_candidates[:3]}"
            )

        return available

    @staticmethod
    def _add_constant(df: pd.DataFrame) -> pd.DataFrame:
        """Add a constant column (intercept) for the GLM."""
        result = df.copy()
        result.insert(0, "const", 1.0)
        return result

    @staticmethod
    def _build_scoreline_matrix(
        lambda_home: float,
        lambda_away: float,
    ) -> List[List[float]]:
        """Build a 7×7 scoreline probability matrix from Poisson lambdas.

        For each cell (h, a) in the matrix:
            P(home=h, away=a) = poisson.pmf(h, lambda_home) × poisson.pmf(a, lambda_away)

        This assumes independence between home and away goals — a standard
        simplification in football modelling.

        The matrix is truncated at 6 goals per team (7 values: 0,1,2,3,4,5,6)
        and renormalised so all 49 cells sum to exactly 1.0.

        Parameters
        ----------
        lambda_home : float
            Expected home goals (Poisson rate parameter).
        lambda_away : float
            Expected away goals (Poisson rate parameter).

        Returns
        -------
        list[list[float]]
            7×7 matrix of scoreline probabilities.
        """
        matrix = []
        total = 0.0

        for h in range(MAX_GOALS):
            row = []
            for a in range(MAX_GOALS):
                # Independent Poisson probabilities
                p = poisson.pmf(h, lambda_home) * poisson.pmf(a, lambda_away)
                row.append(p)
                total += p
            matrix.append(row)

        # Renormalise so the matrix sums to exactly 1.0
        # (truncation at 6 goals removes a small amount of probability mass)
        if total > 0:
            for h in range(MAX_GOALS):
                for a in range(MAX_GOALS):
                    matrix[h][a] /= total

        return matrix
